using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using UnityEngine.InputSystem;
using VContainer.Unity;

using static System.Threading.CancellationTokenSource;

namespace MagicSwords.Features.Input
{
    using PlayerDriven;

    internal interface IUIActionsProvider
    {
        ref Autogenerated_PlayerInputActions.UIActions Get();
    }

    internal sealed class PlayerInputWrapper : Autogenerated_PlayerInputActions, IUIActionsProvider, IAsyncStartable, IDisposable
    {
        private readonly PlayerLoopTiming _initializationPoint;

        private (bool Fetched, UIActions Value) _uiActions;
        private CancellationTokenSource _produceInputUpdates;

        public PlayerInputWrapper(PlayerLoopTiming initializationPoint)
        {
            _initializationPoint = initializationPoint;
        }

        async UniTask IAsyncStartable.StartAsync(CancellationToken cancellation)
        {
            if (await UniTask.Yield(_initializationPoint, cancellation)
                .SuppressCancellationThrow()) return;

            _produceInputUpdates = CreateLinkedTokenSource(cancellation);

            Enable();

            InputFetchLoopAsync(_initializationPoint, _produceInputUpdates.Token)
                .Forget();
        }

        void IDisposable.Dispose()
        {
            _produceInputUpdates.Cancel();

            if (_uiActions.Fetched) _uiActions.Value.Disable();
            Disable();

#       if UNITY_EDITOR
            UnityEngine.Object.DestroyImmediate(asset);
#       else
            Dispose();
#       endif

            _produceInputUpdates.Dispose();
        }

        ref UIActions IUIActionsProvider.Get()
        {
            if (_uiActions.Fetched) return ref _uiActions.Value;

            _uiActions = (Fetched: true, UI);

            return ref _uiActions.Value;
        }

        private static async UniTaskVoid InputFetchLoopAsync(PlayerLoopTiming timing, CancellationToken cancellation = default)
        {
            while (cancellation.IsCancellationRequested is false)
            {
                InputSystem.Update();

                await UniTask.Yield(timing, cancellation)
                    .SuppressCancellationThrow();
            }
        }
    }
}
