using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using UnityEngine.InputSystem;
using VContainer.Unity;

using static System.Threading.CancellationTokenSource;

namespace MagicSwords.Features.Input
{
    using PlayerDriven;

    internal sealed class PlayerInputWrapper : Autogenerated_PlayerInputActions, IAsyncStartable, IDisposable
    {
        private readonly PlayerLoopTiming _initializationPoint;
        private CancellationTokenSource _produceInputUpdates;

        public PlayerInputWrapper(PlayerLoopTiming initializationPoint)
        {
            _initializationPoint = initializationPoint;
        }

        async UniTask IAsyncStartable.StartAsync(CancellationToken cancellation)
        {
            if (await UniTask.Yield(_initializationPoint, cancellation)
                .SuppressCancellationThrow()) return;

            _produceInputUpdates = CreateLinkedTokenSource(cancellation);

            Enable();

            InputFetchLoopAsync(_initializationPoint, _produceInputUpdates.Token)
                .Forget();
        }

        void IDisposable.Dispose()
        {
            _produceInputUpdates.Cancel();

            Disable();

            Dispose();

            _produceInputUpdates.Dispose();
        }

        private static async UniTaskVoid InputFetchLoopAsync(PlayerLoopTiming timing, CancellationToken cancellation = default)
        {
            while (cancellation.IsCancellationRequested is false)
            {
                InputSystem.Update();

                await UniTask.Yield(timing, cancellation)
                    .SuppressCancellationThrow();
            }
        }
    }
}
